### ISSUE TITLE
hamlの導入

### ISSUE THREAD

**Issue by gkumi5638** [gkumi5638/Portfolio#8]
## WHAT - 何を作るのか？
　・htmlの記述をhamlへ

## WHY - 何故作るのか？
　 ・記述の簡略化の為
　
## HOW - どうやって作るのか？
　・gemをインストールする
　・erbファイルをhamlの拡張子へ変換
　・既に記載されているhtmlをhamlへ置き換える

## 参考 URL

* [すごく参考になるページ](https://qiita.com/m_doi/items/1f01fd2b1a52c2c43f1f)
* [ちょっと参考になるページ](http://haml.info/tutorial.html)

## 参考資料
　特になし

**Comment by sagaekeiga** [comment]
ちなみにissueやprでテンプレートを使ってますが、状況によって使い分けてください。
重要で自分の中でも情報を整理したい場合はきちんと内容を埋める、そうでもないときは省略する、といった具合に。

その感覚は、issueを立てる作業を繰り返して行くうちに備わるか、明確な基準を作っていただければ大丈夫だと思います。

**Comment by gkumi5638** [comment]
承知いたしました！
状況によって使い分けていく。
はい。初めは基準がわからないと思いますので、数をこなして感覚を養っていこうと思います。

**Comment by gkumi5638** [comment]
完了！
